# Generated by Django 5.0.1 on 2024-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='supplier_logos/')),
                ('state', models.CharField(max_length=255)),
                ('cost_per_kwh', models.FloatField()),
                ('limit', models.CharField(max_length=255)),
                ('total_customers', models.IntegerField()),
                ('ratings', models.FloatField()),
            ],
        ),
    ]
