# Generated by Django 5.0.1 on 2024-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='../../clark-researches/src/assets/img/fornecedores/')),
                ('estado', models.CharField(max_length=50)),
                ('custo_por_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limite', models.CharField(max_length=100)),
                ('clientes_totais', models.IntegerField()),
                ('avaliacoes_totais', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
